### ISSUE TITLE
get gui stuff out of main and into a gui module

### ISSUE THREAD

**Issue by cougarTech2228** [cougarTech2228/scoutingApp#14]
i would prefer main not to be to cluttered 
just a central starter to the program
i think the gui stuff (which is likely to become very complex) should have its own module

Joe it would be great if you could do this quick as i am not as familiar with the code and you would be able to resolve any minor errors 

also comment comment comment!!!!!!!!!!!!!!!!!!!!!!!!!!!!! the gui stuff and possibly the data stuff as it is very difficult to fallow

**Comment by theJalden** [comment]
Much to my begrudgement.
