### ISSUE TITLE
fix structure 

### ISSUE THREAD

**Issue by cougarTech2228** [cougarTech2228/scoutingApp#21]
I am going to do some structure work in the new branch branch

don’t do any work on the program until I am done ( excluding pit scouting)

**Comment by pythondrew** [comment]
you guys might want to check out
http://git-scm.com/docs/gittutorial

**Comment by pythondrew** [comment]
robots_test.txt? can't find it..

**Comment by theJalden** [comment]
I've put *_test.txt in the git ignore.  It's basically a .txt file where each line is a number of a robot

**Comment by theJalden** [comment]
Still a little messy after the merging, but it should make cleanup a little easier.
