### ISSUE TITLE
the Data modual has a multitude of issues related to the lack of "self" 

### ISSUE THREAD

**Issue by cougarTech2228** [cougarTech2228/scoutingApp#7]

**Comment by cougarTech2228** [comment]
i am not sure how to fix this
it would be helpful if Mr Moore or Joe could take a look at it
or if you could comment some advice

**Comment by theJalden** [comment]
It may just need to take some time and do a soul search.  It sounds like a serious existential chrisis.  I'll help it along its path.

**Comment by theJalden** [comment]
Done
